### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by GoogleCodeExporter** [useataaaaa/acra#103]
```
java.lang.OutOfMemoryError
    at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:154)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:225)
    at org.acra.CrashReportData.isEbcdic(CrashReportData.java:269)
    at org.acra.CrashReportData.load(CrashReportData.java:257)
    at org.acra.ErrorReporter.loadCrashReport(ErrorReporter.java:984)
    at org.acra.ErrorReporter.checkAndSendReports(ErrorReporter.java:959)
    at org.acra.ErrorReporter$ReportsSenderWorker.run(ErrorReporter.java:142)

```

Original issue reported on code.google.com by `droidxl...@gmail.com` on 5 Jan 2012 at 7:16

**Comment by GoogleCodeExporter** [comment]
```
Hello, I'm getting same messages in bug reports. Please give me a note, if I 
can help you identifying bug anyhow.

This issue is only related to Android 4 devices (for me google/yakju 4.0.2 - 
Galaxy Nexus)

I even don't know what is happening on device, if there was crash or what.

I suspect Dalvik Garbage Collector from killing my application in background, 
and not giving ACRA enough memory to fill up report.

APK is signed in production mode with AndroidManifest debuggable=false

Device we're talking about has TOTAL_MEM_SIZE=14311309312 and 
AVAILABLE_MEM_SIZE=4866207744

Device Info: 

BOARD=tuna
BOOTLOADER=PRIMEKK15
BRAND=google
CPU_ABI=armeabi-v7a
CPU_ABI2=armeabi
DEVICE=maguro
DISPLAY=ICL53F
FINGERPRINT=google/yakju/maguro:4.0.2/ICL53F/235179:user/release-keys
HARDWARE=tuna
HOST=vpbs3.mtv.corp.google.com
ID=ICL53F
IS_DEBUGGABLE=false
MANUFACTURER=samsung
MODEL=Galaxy Nexus
PRODUCT=yakju
RADIO=unknown
SERIAL=01498FE71601A016
TAGS=release-keys
TIME=1323307455000
TYPE=user
UNKNOWN=unknown
USER=android-build

java.lang.OutOfMemoryError
    at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:156)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:309)
    at java.io.InputStreamReader.read(InputStreamReader.java:244)
    at java.io.BufferedReader.fillBuf(BufferedReader.java:130)
    at java.io.BufferedReader.read(BufferedReader.java:238)
    at org.acra.CrashReportData.load(CrashReportData.java:321)
    at org.acra.CrashReportData.load(CrashReportData.java:261)
    at org.acra.ErrorReporter.loadCrashReport(ErrorReporter.java:984)
    at org.acra.ErrorReporter.checkAndSendReports(ErrorReporter.java:959)
    at org.acra.ErrorReporter$ReportsSenderWorker.run(ErrorReporter.java:142)

```

Original comment by `Marek.Se...@gmail.com` on 23 Mar 2012 at 7:17

**Comment by GoogleCodeExporter** [comment]
```
Same problem here.
I have several reported OutOfMemory Exception:

LG-MS690 - Android 2.2.1
java.lang.OutOfMemoryError
    at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:171)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:243)
    at org.acra.CrashReportData.isEbcdic(SourceFile:269)
    at org.acra.CrashReportData.load(SourceFile:257)
    at org.acra.ErrorReporter.loadCrashReport(SourceFile:984)
    at org.acra.ErrorReporter.checkAndSendReports(SourceFile:959)
    at org.acra.ErrorReporter$ReportsSenderWorker.run(SourceFile:142)
```

Original comment by `andreass...@gmail.com` on 31 Mar 2012 at 8:20
