### ISSUE TITLE
java.lang.RuntimeException: Package manager has died

### ISSUE THREAD

**Issue by GoogleCodeExporter** [useataaaaa/acra#104]
```
java.lang.RuntimeException: Package manager has died
    at android.app.ApplicationPackageManager.checkPermission(ApplicationPackageManager.java:302)
    at org.acra.ErrorReporter$ReportsSenderWorker.acquireWakeLock(ErrorReporter.java:155)
    at org.acra.ErrorReporter$ReportsSenderWorker.run(ErrorReporter.java:135)
Caused by: android.os.DeadObjectException
    at android.os.BinderProxy.transact(Native Method)
    at android.content.pm.IPackageManager$Stub$Proxy.checkPermission(IPackageManager.java:1430)
    at android.app.ApplicationPackageManager.checkPermission(ApplicationPackageManager.java:300)
    ... 2 more
android.os.DeadObjectException
    at android.os.BinderProxy.transact(Native Method)
    at android.content.pm.IPackageManager$Stub$Proxy.checkPermission(IPackageManager.java:1430)
    at android.app.ApplicationPackageManager.checkPermission(ApplicationPackageManager.java:300)
    at org.acra.ErrorReporter$ReportsSenderWorker.acquireWakeLock(ErrorReporter.java:155)
    at org.acra.ErrorReporter$ReportsSenderWorker.run(ErrorReporter.java:135)

```

Original issue reported on code.google.com by `droidxl...@gmail.com` on 5 Jan 2012 at 7:41

**Comment by GoogleCodeExporter** [comment]
```
There is no more use of acquireWakeLock in the next ACRA version.
Consider this as fixed.
```

Original comment by `kevin.gaudin` on 13 Jan 2012 at 11:16
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `kevin.gaudin` on 13 Jan 2012 at 11:17
- Added labels: **Milestone-Release4.3**

**Comment by GoogleCodeExporter** [comment]
```
This is happening while the Package Manager is checking permissions its= dies 
trying to check them so it will need a try catch on some devices who's package 
manager are unable to complete list check of permissions without dieing.
```

Original comment by `droidxl...@gmail.com` on 13 Jan 2012 at 11:25

**Comment by GoogleCodeExporter** [comment]
```
Hi,
do you know roughly when the next release with this fix will be available?
Any workaround until then? (this is affecting our apps when we push updates)

thanks

```

Original comment by `lbo...@yogiplay.com` on 18 Feb 2012 at 12:00

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I am also affected by this issue. When will the fix be released? Or any 
workaround?
```

Original comment by `dmitry.k...@gmail.com` on 22 Feb 2012 at 8:42

**Comment by GoogleCodeExporter** [comment]
```
I see that this issue is fixed. However, I am using acra version 4.2.3 and I 
got a crash report from one of my users with this exact stack trace.

Am I missing something? Is there a workaround for this?
```

Original comment by `catalin....@gmail.com` on 1 Aug 2012 at 6:49

**Comment by GoogleCodeExporter** [comment]
```
I am using acra 4.2.3 as well and I see a lot of crashes with this exact stack 
trace.
```

Original comment by `FXfil...@gmail.com` on 6 Aug 2012 at 11:08

**Comment by GoogleCodeExporter** [comment]
Original comment by `kevin.gaudin` on 7 Sep 2012 at 9:31
- Changed state: **Verified**

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I am facing the same issue im my application.
I am  not using acra in my application.

I am trying to retrieve list of applications info installed in the deivce in 
aync task.

how package manager issue is related to acra library.
any workarounds ?
```

Original comment by `cholkerp...@gmail.com` on 16 Jan 2014 at 5:57

**Comment by GoogleCodeExporter** [comment]
```
Device used Note 3 
Android 4.3
```

Original comment by `cholkerp...@gmail.com` on 16 Jan 2014 at 5:57

**Comment by GoogleCodeExporter** [comment]
```
Well, if you are not using ACRA, it can't be related to ACRA.
Is there any mention of "org.acra" in your stack trace ?

This issue was caused by what could be an android system issue: sometimes the 
PackageManager just dies for some reason and if your app was calling it at this 
moment it crashes with this error.

One possible cause in your use case seems to be that the list of apps is too 
large: 
https://groups.google.com/forum/#!msg/android-developers/EK4eJPadabs/mCegMDcd7Qk
J
```

Original comment by `kevin.gaudin` on 16 Jan 2014 at 6:27
