### ISSUE TITLE
NullPointerException in org.acra.ErrorReporter$ReportsSenderWorker.run()

### ISSUE THREAD

**Issue by GoogleCodeExporter** [useataaaaa/acra#124]
```
What steps will reproduce the problem?
1. Can't reproduce the problem, only happens sometimes.

What is the expected output? What do you see instead?
Expected Acra to send error report for the exception instead of crashing itself.


What version of the product are you using? On what operating system?
Acra 4.2.3 on Android 2.3.6


Please provide any additional information below.
I am calling ErrorReporter.getInstance().handleException(exception) which 
crashes.
```

Original issue reported on code.google.com by `kristjan...@gmail.com` on 23 Apr 2012 at 10:16

**Comment by GoogleCodeExporter** [comment]
```
I hit this too.  I believe it happens when you call handleException() without 
having initialized ACRA.  It should be a no-op, not a NullPointerException.

E/ACRA    ( 8768): An error occured while writing the report file...
E/ACRA    ( 8768): java.lang.NullPointerException
E/ACRA    ( 8768):  at 
org.acra.ErrorReporter.saveCrashReportFile(ErrorReporter.java:889)
E/ACRA    ( 8768):  at 
org.acra.ErrorReporter.handleException(ErrorReporter.java:740)
E/ACRA    ( 8768):  at 
org.acra.ErrorReporter.handleException(ErrorReporter.java:773)
E/ACRA    ( 8768):  at 
com.zimbra.octopus.android.OctopusService.onHandleIntent(OctopusService.java:416
)
E/ACRA    ( 8768):  at 
android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:59)
E/ACRA    ( 8768):  at android.os.Handler.dispatchMessage(Handler.java:99)
E/ACRA    ( 8768):  at android.os.Looper.loop(Looper.java:132)
E/ACRA    ( 8768):  at android.os.HandlerThread.run(HandlerThread.java:60)
D/ACRA    ( 8768): Mark all pending reports as approved.
E/ACRA    ( 8768): Trying to get ACRA reports but ACRA is not initialized.

```

Original comment by `bbur...@gmail.com` on 20 Jul 2012 at 12:39

**Comment by GoogleCodeExporter** [comment]
```
This should be already fixed in the next release.

Kevin
```

Original comment by `kevin.gaudin` on 20 Jul 2012 at 2:20
- Changed state: **Fixed**
- Added labels: **Milestone-Release4.3**

**Comment by GoogleCodeExporter** [comment]
Original comment by `kevin.gaudin` on 7 Sep 2012 at 9:31
- Changed state: **Verified**
