### ISSUE TITLE
Crash report is not getting updated in google docs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [useataaaaa/acra#128]
```
What steps will reproduce the problem?
1. Have 2G network which is of low bandwidth.
2. Install the app which has crashes(apk is attached with this issue).
3. Launch the installed app which crashes after launching.

What is the expected output? What do you see instead?
Crash report should be sent to the google doc which has below link:
https://docs.google.com/a/cumulations.com/spreadsheet/ccc?key=0AgRaTxmfNL2udGphL
Xp2bEk5VGZ3cjJoWF9heTNSMUE&pli=1#gid=0

What version of the product are you using? On what operating system?
acra-4.2.3 and Gingerbread 2.3

Please provide any additional information below.
Getting the below stack trace of ACRA:


D/StatusBarPolicy(  192): onSignalStrengthsChanged
D/StatusBarService(  192): updateIcon slot=phone_signal index=20 viewIndex=13 
old=StatusBarIcon(pkg=com.android.systemui id=0x7f0200cc level=0 visible=true 
num=0 ) icon=StatusBarIcon(pkg=com.android.systemui id=0x7f0200cc level=0 
visible=true num=0 )
E/ACRA    ( 1419): Failed to send crash report for 
1338393718000-approved.stacktrace
E/ACRA    ( 1419): org.acra.sender.ReportSenderException: Error while sending 
report to Google Form.
E/ACRA    ( 1419):  at 
org.acra.sender.GoogleFormSender.send(GoogleFormSender.java:64)
E/ACRA    ( 1419):  at 
org.acra.ErrorReporter.sendCrashReport(ErrorReporter.java:850)
E/ACRA    ( 1419):  at 
org.acra.ErrorReporter.checkAndSendReports(ErrorReporter.java:960)
E/ACRA    ( 1419):  at 
org.acra.ErrorReporter$ReportsSenderWorker.run(ErrorReporter.java:142)
E/ACRA    ( 1419): Caused by: java.net.SocketTimeoutException: Read timed out
E/ACRA    ( 1419):  at 
org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_read(Native Method)
E/ACRA    ( 1419):  at 
org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl$SSLInputStream.read(Open
SSLSocketImpl.java:788)
E/ACRA    ( 1419):  at 
org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInp
utBuffer.java:103)
E/ACRA    ( 1419):  at 
org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInput
Buffer.java:191)
E/ACRA    ( 1419):  at 
org.apache.http.impl.conn.DefaultResponseParser.parseHead(DefaultResponseParser.
java:82)
E/ACRA    ( 1419):  at 
org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:1
74)
E/ACRA    ( 1419):  at 
org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(Abstract
HttpClientConnection.java:179)
E/ACRA    ( 1419):  at 
org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultC
lientConnection.java:235)
E/ACRA    ( 1419):  at 
org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(Abstra
ctClientConnAdapter.java:259)
E/ACRA    ( 1419):  at 
org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecut
or.java:279)
E/ACRA    ( 1419):  at 
org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:12
1)
E/ACRA    ( 1419):  at 
org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirecto
r.java:421)
E/ACRA    ( 1419):  at 
org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:5
55)
E/ACRA    ( 1419):  at 
org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:4
87)
E/ACRA    ( 1419):  at org.acra.util.HttpRequest.sendPost(HttpRequest.java:109)
E/ACRA    ( 1419):  at org.acra.util.HttpRequest.sendPost(HttpRequest.java:80)
E/ACRA    ( 1419):  at org.acra.util.HttpUtils.doPost(HttpUtils.java:59)
E/ACRA    ( 1419):  at 
org.acra.sender.GoogleFormSender.send(GoogleFormSender.java:62)
E/ACRA    ( 1419):  ... 3 more
D/ACRA    ( 1419): #checkAndSendReports - finish
E/AndroidRuntime( 1419): FATAL EXCEPTION: main
E/AndroidRuntime( 1419): java.lang.RuntimeException: Unable to start activity 
ComponentInfo{com.android.reportdialog/com.android.reportdialog.ReportDialogExam
pleActivity}: java.lang.NullPointerException
E/AndroidRuntime( 1419):    at 
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1830)
E/AndroidRuntime( 1419):    at 
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1851)
E/AndroidRuntime( 1419):    at 
android.app.ActivityThread.access$1500(ActivityThread.java:132)
E/AndroidRuntime( 1419):    at 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1038)
E/AndroidRuntime( 1419):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 1419):    at android.os.Looper.loop(Looper.java:143)
E/AndroidRuntime( 1419):    at 
android.app.ActivityThread.main(ActivityThread.java:4277)
E/AndroidRuntime( 1419):    at java.lang.reflect.Method.invokeNative(Native 
Method)
E/AndroidRuntime( 1419):    at java.lang.reflect.Method.invoke(Method.java:507)
E/AndroidRuntime( 1419):    at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
E/AndroidRuntime( 1419):    at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/AndroidRuntime( 1419):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 1419): Caused by: java.lang.NullPointerException
E/AndroidRuntime( 1419):    at 
com.android.reportdialog.ReportDialogExampleActivity.onCreate(ReportDialogExampl
eActivity.java:14)
E/AndroidRuntime( 1419):    at 
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
E/AndroidRuntime( 1419):    at 
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1794)
E/AndroidRuntime( 1419):    ... 11 more
W/ActivityManager(  123):   Force finishing activity 
com.android.reportdialog/.ReportDialogExampleActivity
W/ActivityManager(  123): Activity pause timeout for HistoryRecord{40b556d0 
com.android.reportdialog/.ReportDialogExampleActivity}
D/SensorService(  123): disable: BMA150 3-axis Accelerometer
D/StatusBarService(  192): updateIcon slot=data_connection index=18 
viewIndex=12 old=StatusBarIcon(pkg=com.android.systemui id=0x7f02008e level=0 
visible=true num=0 ) icon=StatusBarIcon(pkg=com.android.systemui id=0x7f0200a2 
level=0 visible=true num=0 )
D/SensorService(  123): SensorDevice::activate: handle = 0x0, enabled = 0x0
D/Sensors (  123): [AkmSensor::enable] mEnabled = 0x0
D/SensorService(  123): pid=123, uid=1000

```

Original issue reported on code.google.com by `p...@cumulations.com` on 30 May 2012 at 4:35

Attachments:
- [ReportDialogExample.apk](https://storage.googleapis.com/google-code-attachments/acra/issue-128/comment-0/ReportDialogExample.apk)

**Comment by GoogleCodeExporter** [comment]
```
Timeouts have been adjusted in ACRA 4.3.0.
You can also configure higher values with ReportsCrashes.connectionTimeout and 
ReportsCrashes.socketTimeout

If sending a report reaches the timeout, the report is kept and sent again on 
next crash or application restart.
```

Original comment by `kevin.gaudin` on 7 Sep 2012 at 10:05
- Changed state: **WontFix**
