### ISSUE TITLE
ACRA Crash in 4.3.0b2 NullPointerException 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [useataaaaa/acra#140]
```
What steps will reproduce the problem?
1. Install latest version of acra (4.3.0b2)
2. No clue... 

java.lang.NullPointerException
        at android.os.Parcel.readException(Parcel.java:1328)
        at android.os.Parcel.readException(Parcel.java:1276)
        at android.view.IWindowSession$Stub$Proxy.relayout(IWindowSession.java:561)
        at android.view.ViewRoot.relayoutWindow(ViewRoot.java:2709)
        at android.view.ViewRoot.performTraversals(ViewRoot.java:953)
        at android.view.ViewRoot.handleMessage(ViewRoot.java:1865)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:130)
        at org.acra.ErrorReporter$1.run(ErrorReporter.java:564)




What version of the product are you using? On what operating system?
Android 2.3.4

Please provide any additional information below.

```

Original issue reported on code.google.com by `federico...@gmail.com` on 1 Sep 2012 at 2:00

**Comment by GoogleCodeExporter** [comment]
```
Hi,

Are you able to reproduce that error ? How frequently does this happen ?

Kevin
```

Original comment by `kevin.gaudin` on 1 Sep 2012 at 10:32

**Comment by GoogleCodeExporter** [comment]
```
I haven't been able to reproduce the error, since its happening on remote 
machines that I dont have access to

I also saw this one:

"java.lang.NullPointerException
    at android.os.Parcel.readException(Parcel.java:1328)
    at android.os.Parcel.readException(Parcel.java:1276)
    at android.view.IWindowSession$Stub$Proxy.add(IWindowSession.java:446)
    at android.view.ViewRoot.setView(ViewRoot.java:502)
    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:207)
    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:121)
    at android.widget.Toast$TN.handleShow(Toast.java:412)
    at android.widget.Toast$TN$1.run(Toast.java:341)
    at android.os.Handler.handleCallback(Handler.java:587)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:130)
    at org.acra.ErrorReporter$1.run(ErrorReporter.java:564)
"

I haven't seen it too frequently about 5 times in my logs  
```

Original comment by `federico...@gmail.com` on 1 Sep 2012 at 10:54
