### ISSUE TITLE
Failed to send crash reports : Package is not a constant in org.acra.ReportField

### ISSUE THREAD

**Issue by GoogleCodeExporter** [useataaaaa/acra#152]
```
I am trying to put acra in my android app and getting this error on every 
device and emulator. I tried the to use my custom server to send crash logs, 
when it didn't work i tried hockey app and when it didn't work i tried sending 
email .
But everytime i get this error

 Failed to send crash reports for 5465d8bb-8a25-419a-8470-eab8ae6f1bae.stacktrace
    java.lang.IllegalArgumentException: Package is not a constant in org.acra.ReportField
            at java.lang.Enum.valueOf(Enum.java:198)
            at org.acra.CrashReportPersister.load(CrashReportPersister.java:264)
            at org.acra.CrashReportPersister.load(CrashReportPersister.java:75)
            at org.acra.SendWorker.checkAndSendReports(SendWorker.java:140)
            at org.acra.SendWorker.run(SendWorker.java:77)




This is the complete log
03-08 01:13:38.365    1448-1448/com.test.application D/ACRA﹕ ACRA is enabled 
for com.test.application, intializing...
03-08 01:13:38.369    1448-1448/com.test.application D/ACRA﹕ Looking for 
error files in /data/data/com.test.application/files
03-08 01:13:54.521    1495-1495/? D/ACRA﹕ ACRA is enabled for 
com.test.application, intializing...
03-08 01:13:54.525    1495-1495/? D/ACRA﹕ Looking for error files in 
/data/data/com.test.application/files
03-08 01:13:54.525    1495-1495/? D/ACRA﹕ Looking for error files in 
/data/data/com.test.application/files
03-08 01:13:54.525    1495-1495/? V/ACRA﹕ About to start ReportSenderWorker 
from #checkReportOnApplicationStart
03-08 01:13:54.533    1495-1509/? D/ACRA﹕ #checkAndSendReports - start
03-08 01:13:54.533    1495-1509/? D/ACRA﹕ Looking for error files in 
/data/data/com.test.application/files
03-08 01:13:54.533    1495-1509/? I/ACRA﹕ Sending file 
5465d8bb-8a25-419a-8470-eab8ae6f1bae.stacktrace
03-08 01:13:54.533    1495-1509/? E/ACRA﹕ Failed to send crash reports for 
5465d8bb-8a25-419a-8470-eab8ae6f1bae.stacktrace
    java.lang.IllegalArgumentException: Package is not a constant in org.acra.ReportField
            at java.lang.Enum.valueOf(Enum.java:198)
            at org.acra.CrashReportPersister.load(CrashReportPersister.java:264)
            at org.acra.CrashReportPersister.load(CrashReportPersister.java:75)
            at org.acra.SendWorker.checkAndSendReports(SendWorker.java:140)
            at org.acra.SendWorker.run(SendWorker.java:77)
03-08 01:13:54.533    1495-1509/? D/ACRA﹕ #checkAndSendReports - finish
```

Original issue reported on code.google.com by `ashishgu...@gmail.com` on 8 Mar 2014 at 1:20

**Comment by GoogleCodeExporter** [comment]
```
I am getting same error please help
```

Original comment by `it.ashut...@gmail.com` on 28 Jun 2015 at 11:13

**Comment by GoogleCodeExporter** [comment]
```
here is the complete log

06-28 16:41:51.186: D/ACRA(29963): Retrieve application default 
SharedPreferences.
06-28 16:41:51.189: D/ACRA(29963): Set OnSharedPreferenceChangeListener.
06-28 16:41:51.191: D/ACRA(29963): ACRA is enabled for com.example.demotest, 
intializing...
06-28 16:41:51.208: D/ACRA(29963): Looking for error files in 
/data/data/com.example.demotest/files
06-28 16:42:01.228: W/ResponseProcessCookies(29963): Invalid cookie header: 
"Set-Cookie: 
NID=68=StlVZFrdj3Jwdkx4o4qmed1sc3ka5KfOqV22mH_ZLX3-PuwZlfm6Ngg3iVVJDhn2nQGuSHDIl
0L7JhvrjFjX65pkRXm7gFSKcwZf8DH3D3S70VnyrnZqS2vFj1KhFNk_;Domain=.google.com;Path=
/;Expires=Mon, 28-Dec-2015 11:12:02 GMT;HttpOnly". Unable to parse expires 
attribute: Mon
06-28 16:42:01.229: W/ResponseProcessCookies(29963): Invalid cookie header: 
"Set-Cookie: 
NID=68=G0tVD885cK2agdaenSv3GJG0VJoTvsPl3MZiRwourUp_EWF9Na1l9UZI9WwlIgf1HI7PXdROo
7F0p5V4nazzX5ESDo5u2PinO1Ox3tudfUYyaWNpYF10ARpNjZKp-LDd;Domain=.google.com;Path=
/;Expires=Mon, 28-Dec-2015 11:12:02 GMT;HttpOnly". Unable to parse expires 
attribute: Mon
06-28 16:42:01.231: E/ACRA(29963): Failed to send crash report for 
1435489919000-approved.stacktrace
06-28 16:42:01.231: E/ACRA(29963): org.acra.sender.ReportSenderException: Error 
while sending report to Google Form.
06-28 16:42:01.231: E/ACRA(29963):  at 
org.acra.sender.GoogleFormSender.send(GoogleFormSender.java:64)
06-28 16:42:01.231: E/ACRA(29963):  at 
org.acra.ErrorReporter.sendCrashReport(ErrorReporter.java:850)
06-28 16:42:01.231: E/ACRA(29963):  at 
org.acra.ErrorReporter.checkAndSendReports(ErrorReporter.java:960)
06-28 16:42:01.231: E/ACRA(29963):  at 
org.acra.ErrorReporter$ReportsSenderWorker.run(ErrorReporter.java:142)
06-28 16:42:01.231: E/ACRA(29963): Caused by: java.io.IOException: Host 
returned error code 404
06-28 16:42:01.231: E/ACRA(29963):  at 
org.acra.util.HttpRequest.sendPost(HttpRequest.java:115)
06-28 16:42:01.231: E/ACRA(29963):  at 
org.acra.util.HttpRequest.sendPost(HttpRequest.java:80)
06-28 16:42:01.231: E/ACRA(29963):  at 
org.acra.util.HttpUtils.doPost(HttpUtils.java:59)
06-28 16:42:01.231: E/ACRA(29963):  at 
org.acra.sender.GoogleFormSender.send(GoogleFormSender.java:62)
06-28 16:42:01.231: E/ACRA(29963):  ... 3 more
06-28 16:42:01.231: D/ACRA(29963): #checkAndSendReports - finish
06-28 16:42:03.880: E/ACRA(29963): DemoTest fatal error : Unable to start 
activity ComponentInfo{com.example.demotest/com.example.demotest.MainActivity}: 
java.lang.ArithmeticException: divide by zero
06-28 16:42:03.880: E/ACRA(29963): java.lang.RuntimeException: Unable to start 
activity ComponentInfo{com.example.demotest/com.example.demotest.MainActivity}: 
java.lang.ArithmeticException: divide by zero
06-28 16:42:03.880: E/ACRA(29963):  at 
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2314)
06-28 16:42:03.880: E/ACRA(29963):  at 
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388)
06-28 16:42:03.880: E/ACRA(29963):  at 
android.app.ActivityThread.access$800(ActivityThread.java:148)
06-28 16:42:03.880: E/ACRA(29963):  at 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
06-28 16:42:03.880: E/ACRA(29963):  at 
android.os.Handler.dispatchMessage(Handler.java:102)
06-28 16:42:03.880: E/ACRA(29963):  at android.os.Looper.loop(Looper.java:135)
06-28 16:42:03.880: E/ACRA(29963):  at 
android.app.ActivityThread.main(ActivityThread.java:5312)
06-28 16:42:03.880: E/ACRA(29963):  at java.lang.reflect.Method.invoke(Native 
Method)
06-28 16:42:03.880: E/ACRA(29963):  at 
java.lang.reflect.Method.invoke(Method.java:372)
06-28 16:42:03.880: E/ACRA(29963):  at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
06-28 16:42:03.880: E/ACRA(29963):  at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
06-28 16:42:03.880: E/ACRA(29963): Caused by: java.lang.ArithmeticException: 
divide by zero
06-28 16:42:03.880: E/ACRA(29963):  at 
com.example.demotest.MainActivity.onCreate(MainActivity.java:16)
06-28 16:42:03.880: E/ACRA(29963):  at 
android.app.Activity.performCreate(Activity.java:5953)
06-28 16:42:03.880: E/ACRA(29963):  at 
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1128)
06-28 16:42:03.880: E/ACRA(29963):  at 
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2267)
06-28 16:42:03.880: E/ACRA(29963):  ... 10 more
06-28 16:42:03.880: I/Process(29963): Sending signal. PID: 29963 SIG: 9
06-28 16:42:04.074: D/ACRA(30654): Retrieve application default 
SharedPreferences.
06-28 16:42:04.075: D/ACRA(30654): Set OnSharedPreferenceChangeListener.
06-28 16:42:04.079: D/ACRA(30654): ACRA is enabled for com.example.demotest, 
intializing...
06-28 16:42:04.098: D/ACRA(30654): Looking for error files in 
/data/data/com.example.demotest/files
06-28 16:42:04.099: V/ACRA(30654): About to start ReportSenderWorker from 
#checkReportOnApplicationStart
06-28 16:42:04.103: D/ACRA(30654): Add user comment to null
06-28 16:42:04.103: D/ACRA(30654): #checkAndSendReports - start
06-28 16:42:04.104: D/ACRA(30654): Looking for error files in 
/data/data/com.example.demotest/files
06-28 16:42:04.104: I/ACRA(30654): Sending file 
1435489919000-approved.stacktrace
06-28 16:42:04.114: D/ACRA(30654): Sending report 
60304030-683d-4fad-8c37-55b49f200fc2
06-28 16:42:04.114: D/ACRA(30654): Connect to 
https://spreadsheets.google.com/formResponse?formkey=1v5oxhDQGrygzOiGgvT_OnDVpYz
E3AaRJSPouv-VpbMg&ifq
06-28 16:42:04.133: D/ACRA(30654): Setting httpPost headers
06-28 16:42:04.136: D/ACRA(30654): Sending request to 
https://spreadsheets.google.com/formResponse?formkey=1v5oxhDQGrygzOiGgvT_OnDVpYz
E3AaRJSPouv-VpbMg&ifq
06-28 16:42:04.296: D/AndroidRuntime(30654): Shutting down VM
06-28 16:42:04.297: E/ACRA(30654): ACRA caught a RuntimeException exception for 
com.example.demotest. Building report.
06-28 16:42:04.298: D/ACRA(30654): Retrieve application default 
SharedPreferences.
06-28 16:42:04.350: D/OpenGLRenderer(30654): Render dirty regions requested: 
true
06-28 16:42:04.357: I/ACRA(30654): READ_LOGS not allowed. ACRA will not include 
LogCat and DropBox data.
06-28 16:42:04.370: D/Atlas(30654): Validating map...
06-28 16:42:04.407: I/Adreno-EGL(30654): <qeglDrvAPI_eglInitialize:410>: EGL 
1.4 QUALCOMM build: 
AU_LINUX_ANDROID_LA.BF.1.1_RB1.05.00.00.002.030_msm8226_LA.BF.1.1_RB1__release_A
U ()
06-28 16:42:04.407: I/Adreno-EGL(30654): OpenGL ES Shader Compiler Version: 
E031.25.03.00
06-28 16:42:04.407: I/Adreno-EGL(30654): Build Date: 12/04/14 Thu
06-28 16:42:04.407: I/Adreno-EGL(30654): Local Branch: 
06-28 16:42:04.407: I/Adreno-EGL(30654): Remote Branch: quic/LA.BF.1.1_rb1.14
06-28 16:42:04.407: I/Adreno-EGL(30654): Local Patches: NONE
06-28 16:42:04.407: I/Adreno-EGL(30654): Reconstruct Branch: 
AU_LINUX_ANDROID_LA.BF.1.1_RB1.05.00.00.002.030 +  NOTHING
06-28 16:42:04.409: I/OpenGLRenderer(30654): Initialized EGL, version 1.4

```

Original comment by `it.ashut...@gmail.com` on 28 Jun 2015 at 11:15
