### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: public abstract int

### ISSUE THREAD

**Issue by GoogleCodeExporter** [useataaaaa/acra#49]
```
ACRA 3.1.1, officicial library.
Only get this reported once yet inside of my developer section of the market:

java.lang.RuntimeException: Unable to create application 
com.bitmotor.android.posterousit.PosterousItApp: 
java.lang.IllegalArgumentException: public abstract int 
org.acra.annotation.ReportsCrashes.resDialogText()
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4247)
at android.app.ActivityThread.access$3000(ActivityThread.java:125)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2071)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:4627)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: public abstract int 
org.acra.annotation.ReportsCrashes.resDialogText()
at 
org.apache.harmony.lang.annotation.AnnotationFactory.invoke(AnnotationFactory.ja
va:309)
at $Proxy0.resDialogText(Native Method)
at org.acra.ACRA.initCrashResources(ACRA.java:214)
at org.acra.ACRA.initAcra(ACRA.java:185)
at org.acra.ACRA.init(ACRA.java:166)
at 
com.bitmotor.android.posterousit.PosterousItApp.onCreate(PosterousItApp.java:77)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:969)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4244)
... 10 more
```

Original issue reported on code.google.com by `grischa....@gmail.com` on 17 Apr 2011 at 12:09

**Comment by GoogleCodeExporter** [comment]
```
Really strange, I can't see what could have lead to an IllegalArgumentException 
when reading the value from this annotation method...
```

Original comment by `kevin.gaudin` on 8 May 2011 at 8:32
- Added labels: **Priority-Low**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
Closing this as it is now rather old and was reported on a now unsupported 
version. If it ever occurs on ACRA v4.2.3, please reopen the issue.
```

Original comment by `kevin.gaudin` on 25 Nov 2011 at 11:27
- Changed state: **WontFix**
