### ISSUE TITLE
NPE on 4.2.1b - custom exception handling

### ISSUE THREAD

**Issue by GoogleCodeExporter** [useataaaaa/acra#55]
```
This error just showed up in my Google Developer Console.
I am pretty sure ACRA should have send a report for a custom exception caught 
by a simple try/catch statement. Anything I can do about this?

java.lang.NullPointerException
 at org.acra.ErrorReporter.java.lang.String[] getCrashReportFilesList()(Unknown Source)
 at org.acra.ErrorReporter.void approvePendingReports()(Unknown Source)
                           void init(android.content.Context)
                           org.acra.ErrorReporter$ReportsSenderWorker handleException(java.lang.Throwable,org.acra.ReportingInteractionMode)
                           org.acra.ErrorReporter$ReportsSenderWorker handleException(java.lang.Throwable)
                           void notifySendReport(java.lang.String)
                           void sendCrashReport(android.content.Context,org.acra.CrashReportData)
                           java.lang.String saveCrashReportFile(java.lang.String,org.acra.CrashReportData)
                           void checkAndSendReports(android.content.Context,boolean)
                           void setReportingInteractionMode(org.acra.ReportingInteractionMode)
                           void deletePendingReports(boolean,boolean,int)
                           void addReportSender(org.acra.sender.ReportSender)
                           void setAppStartDate(android.text.format.Time)
                           void access$100(android.content.Context,java.lang.String,java.lang.String,java.lang.String)
 at org.acra.ErrorReporter.void approvePendingReports()(Unknown Source)
                           void init(android.content.Context)
                           org.acra.ErrorReporter$ReportsSenderWorker handleException(java.lang.Throwable,org.acra.ReportingInteractionMode)
                           org.acra.ErrorReporter$ReportsSenderWorker handleException(java.lang.Throwable)
                           void notifySendReport(java.lang.String)
                           void sendCrashReport(android.content.Context,org.acra.CrashReportData)
                           java.lang.String saveCrashReportFile(java.lang.String,org.acra.CrashReportData)
                           void checkAndSendReports(android.content.Context,boolean)
                           void setReportingInteractionMode(org.acra.ReportingInteractionMode)
                           void deletePendingReports(boolean,boolean,int)
                           void addReportSender(org.acra.sender.ReportSender)
                           void setAppStartDate(android.text.format.Time)
                           void access$100(android.content.Context,java.lang.String,java.lang.String,java.lang.String)
 at org.acra.ErrorReporter.void approvePendingReports()(Unknown Source)
                           void init(android.content.Context)
                           org.acra.ErrorReporter$ReportsSenderWorker handleException(java.lang.Throwable,org.acra.ReportingInteractionMode)
                           org.acra.ErrorReporter$ReportsSenderWorker handleException(java.lang.Throwable)
                           void notifySendReport(java.lang.String)
                           void sendCrashReport(android.content.Context,org.acra.CrashReportData)
                           java.lang.String saveCrashReportFile(java.lang.String,org.acra.CrashReportData)
                           void checkAndSendReports(android.content.Context,boolean)
                           void setReportingInteractionMode(org.acra.ReportingInteractionMode)
                           void deletePendingReports(boolean,boolean,int)
                           void addReportSender(org.acra.sender.ReportSender)
                           void setAppStartDate(android.text.format.Time)
                           void access$100(android.content.Context,java.lang.String,java.lang.String,java.lang.String)
 at com.designoid.therealsync.TRSService$1.void run()(Unknown Source)
 at android.os.Handler.handleCallback(Handler.java:587)
 at android.os.Handler.dispatchMessage(Handler.java:92)
 at android.os.Looper.loop(Looper.java:123)
 at android.app.ActivityThread.main(ActivityThread.java:4627)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:521)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
 at dalvik.system.NativeStart.main(Native Method)

```

Original issue reported on code.google.com by `t.fohlmeister` on 13 Jun 2011 at 1:58

**Comment by GoogleCodeExporter** [comment]
```
The stack trace is quite strange... is this a simple copy/paste from the market 
console or did you edit it ?
```

Original comment by `kevin.gaudin` on 13 Jun 2011 at 8:40

**Comment by GoogleCodeExporter** [comment]
```
I can't read too much out it neither. This is directly copy/pasted from market 
and retraced using the usual procedure.
Actually all of my market errors look like this...is there something I can 
change?
```

Original comment by `t.fohlmeister` on 14 Jun 2011 at 9:08

**Comment by GoogleCodeExporter** [comment]
```
Applied a fix on what I could guess... maybe due to context not inialized... I 
can't do anything more with that stacktrace.
```

Original comment by `kevin.gaudin` on 14 Jun 2011 at 11:47
- Changed state: **Fixed**
- Added labels: **Milestone-Release4.2**

**Comment by GoogleCodeExporter** [comment]
Original comment by `kevin.gaudin` on 22 Dec 2011 at 9:08
- Changed state: **Verified**
