### ISSUE TITLE
IllegalArgumentException: entry.1.single is not a constant in class org.acra.ReportField

### ISSUE THREAD

**Issue by GoogleCodeExporter** [useataaaaa/acra#64]
```
Here is the stack trace

Failed to send crash reports
java.lang.IllegalArgumentException: entry.1.single is not a constant in class 
org.acra.ReportField
at java.lang.Enum.valueOf(Enum.java:176)
at org.acra.CrashReportData.load(CrashReportData.java:412)
at org.acra.CrashReportData.load(CrashReportData.java:261)
at org.acra.ErrorReporter.loadCrashReport(ErrorReporter.java:984)
at org.acra.ErrorReporter.checkAndSendReports(ErrorReporter.java:959)
at org.acra.ErrorReporter$ReportsSenderWorker.run(ErrorReporter.java:142)

It happens everytime the app opens.  I just switched from 3.x to latest 4.x 
stable release.

Happening on a Nexus S 2.3.4, and not happening on another device I have.

Happy to look into it more if there are specific details you want.

Thanks for an awesome tool!
```

Original issue reported on code.google.com by `dudeman...@gmail.com` on 18 Jul 2011 at 9:08

**Comment by GoogleCodeExporter** [comment]
```
Exactly the same case. Just updated from 2.3.4 and ran in Nexus S
```

Original comment by `joanpu...@gmail.com` on 30 Jul 2011 at 3:25

**Comment by GoogleCodeExporter** [comment]
```
Same problem for me, just updated from 3.x to 4.x
```

Original comment by `b...@sewichi.com` on 25 Aug 2011 at 9:54

**Comment by GoogleCodeExporter** [comment]
```
Exact same stack trace for the following device:

BRAND=samsung
DEVICE=GT-P7510
MANUFACTURER=samsung
MODEL=GT-P7510
PRODUCT=GT-P7510

HTH. Acra v4.1.2.
```

Original comment by `hbls00...@gmail.com` on 30 Aug 2011 at 9:07

**Comment by GoogleCodeExporter** [comment]
```
No more reports since 1 year, no reports on ACRA 4.2.3 and now ACRA 4.3.0 is 
out.
It might have been fixed in latest versions.
```

Original comment by `kevin.gaudin` on 7 Sep 2012 at 9:59
- Changed state: **Verified**

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I have same problem in Arca v.4.4.0
and It may happen when OS ver is 2.3.
It's not problem when OS ver is 4.0 or higher.
```

Original comment by `yym...@gmail.com` on 7 Oct 2013 at 8:55
