### ISSUE TITLE
Unable to start activity

### ISSUE THREAD

**Issue by GoogleCodeExporter** [useataaaaa/acra#9]
```
java.lang.RuntimeException: Unable to start activity 
ComponentInfo{com.alocaly.crashreport/com.alocaly.crashreport.CrashTestActivity}
: java.lang.NullPointerException
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2496)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2512)
    at android.app.ActivityThread.access$2200(ActivityThread.java:119)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1863)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:123)
    at android.app.ActivityThread.main(ActivityThread.java:4363)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:521)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
    at com.alocaly.crashreport.CrashTestActivity.onCreate(CrashTestActivity.java:17)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2459)
    ... 11 more
java.lang.NullPointerException
    at com.alocaly.crashreport.CrashTestActivity.onCreate(CrashTestActivity.java:17)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2459)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2512)
    at android.app.ActivityThread.access$2200(ActivityThread.java:119)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1863)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:123)
    at android.app.ActivityThread.main(ActivityThread.java:4363)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:521)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
    at dalvik.system.NativeStart.main(Native Method)



What version of the product are you using? On what operating system?
acra-2.0.3
android 2.1
```

Original issue reported on code.google.com by `david.ch...@gmail.com` on 6 Sep 2010 at 8:33

**Comment by GoogleCodeExporter** [comment]
```
This is the exception thrown by the crash test application used by the library 
developers.

If you have it in your crash report, this is just an example of crash report 
which is included in the file template that you imported in Google Docs. You 
can delete it.
```

Original comment by `kevin.gaudin` on 6 Sep 2010 at 9:48
- Added labels: **Priority-Low**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
Original comment by `kevin.gaudin` on 15 Nov 2010 at 10:24
- Changed state: **Invalid**
